### ISSUE TITLE
plugin unable to open sdt file

### ISSUE THREAD

**Issue by jrapaka1** [zoccoler/napari-flim-phasor-plotter#56] opened 2024-05-30 18:31 UTC
I am trying to open an sdt file retreived from a Becker Hickl FLIM instrument, but I am getting the following error message:
ValueError: could not broadcast input array from shape (1024,1024,1024) into shape (1024,1024)

Is there any way for me to convert the 3D array into 2D? Or is there some other troubleshooting needed?

**Comment by zoccoler** [comment] 2024-06-19 11:49
Hi @jrapaka1 ,

Sorry for the delay, I was busy with other projects. I don't have access to a 3D .sdt data to test this. Could you provide a link to an example image so that I can try to reproduce it?

Also, could you please paste a screenshot of the whole Error message? I need more information to understand where the error actually comes from.

**Comment by jrapaka1** [comment] 2024-06-19 13:37
Here is a google drive link to one of our .sdt files: https://drive.google.com/file/d/1TccWcQdkwLnN1ayhKw_rRI_DNMu1LLsI/view?usp=sharing

Here is a screenshot of the error traceback:
<img width="1052" alt="naparierrorSS" src="https://github.com/zoccoler/napari-flim-phasor-plotter/assets/171189705/95082396-367c-426c-99dd-f1a60d32aa54">

**Comment by zoccoler** [comment] 2024-06-25 15:01
Hi @jrapaka1 ,

It seems you have multiple data sets of different shapes in your sdt file. The first one has dimensions (1024, 1024, 1024) and the second has dimensions (1024, 1024). Since the shapes don't match, we get this error. I would assume your first array is your raw FLIM data, am I right? The second seems to be the summed intensity or average image.

I am working on a fix to open the right raw image. If I open only the first array, I get the following plot:

![image](https://github.com/zoccoler/napari-flim-phasor-plotter/assets/26173597/c8d5ed56-259e-43ab-a79e-040e4374dfde)
Does it make sense? It took quite some time (around 2-3minutes for me) to generate the plot since your FLIM dimension is relatively large, but it seems to be better than in #57 .

**Comment by jrapaka1** [comment] 2024-06-25 18:35
Thank you so much! That phasor looks much more like what we expected.

**Comment by zoccoler** [comment] 2024-07-02 06:33
Closed via #59

**Closed by zoccoler** 2024-07-02 06:33 UTC
